name: "Scan open ports action"
description: "Scan open tcp ports from hostname"
author: 'Tristan Robert'
branding:
  icon: 'activity'  
  color: 'green'
inputs:
  host:
    description: 'The host to scan with nmap'
    required: true
  image:
    description: 'Docker image to run nmap'
    default: 'instrumentisto/nmap'
  outputDir:
    description: 'Folder for scan reports'
    default: 'output'
  outputFile:
    description: 'File name for scan reports'
    default: 'nmap.json'
  raw:
    description: 'Raw or reduced JSON'
    default: false
  withVulnerabilities:
    description: 'if true scan vulners NSE else open ports only'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
      
