name: "tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  action:
    name: Test GH Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Locally
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: "portscan-action"
      - name: Checkout Github
        uses: actions/checkout@v2
        if: ${{ !env.ACT }}
      - name: scan scanme.nmap.org
        uses: ./
        with:
          host: scanme.nmap.org
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: nmap json report
          path: 'output/'
      - name: test output
        run: |
          tool=$(echo $(cat output/openports.json | jq '. | length'))
          if [[ ! "${tool[@]}" == 1 ]]; then
            exit 1
          fi